#!/bin/sh

JAVA=`which java`

JVM_OPTS="-Xms512M -Xmx1024M -Xss512K -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9998 \
      -XX:ReservedCodeCacheSize=192m \
      -XX:PermSize=128m \
      -XX:MaxPermSize=256M \
      -XX:+CMSClassUnloadingEnabled \
      -XX:+HeapDumpOnOutOfMemoryError \
      -XX:+PrintCommandLineFlags \
      -Dhttp.port=9090 \
      -Dfile.encoding=UTF-8 \
"

#      -XX:+CITime \
#      -XX:+PrintGC \
#      -XX:+PrintGCDetails \
#      -XX:+PrintGCTimeStamps \
#      -XX:+PerfDataSaveToFile \
#      -XX:HeapDumpPath=./dumps/java_pid<pid>.hprof \
#      -XX:ErrorFile=./dumps/hs_err_pid<pid>.log \
#      -agentpath:/Applications/YourKit_Java_Profiler_2014_build_14108.app/Contents/Resources/bin/mac/libyjpagent.jnilib \

ACTIVATOR_VERSION="1.2.10"
ACTIVATOR_HOME="/usr/local/Cellar/typesafe-activator/${ACTIVATOR_VERSION}/libexec"
ACTIVATOR_OPTS="-Dsbt.jse.engineType=Node -Dactivator.home=${ACTIVATOR_HOME}"

"${JAVA}" ${JVM_OPTS} ${ACTIVATOR_OPTS} -jar ${ACTIVATOR_HOME}/activator-launch-1.2.10.jar

